### PR TITLE
Allow negative numbers (and text, unfortunately) on update score.

### LINKED ISSUE #1: Negative points are not possible
In "Doppelkopf" many people count positive for the two winners and negative for the two loosers... This doesnt Seen to be possible

### PR DESCRIPTION
**Pull request by rengolin**
Using number format restricted usage to positive numbers only (no minus sign). Unfortunately, using text format defaults to text keyboard.

I need to think of a way to open a numeric keyboard while keeping the text format.

Fixes #1

### CODE REVIEW

**Comment by StefanBrand** [comment]
What about `TYPE_CLASS_PHONE`? I believe that this should return a numeric keyboard _with_ the minus symbol.

**Comment by rengolin** [comment]
Good point. I need to find the Android Studio and try to build this thing again... :)

Feel free to submit a pull request on that one, though, should be a no brainer.

**Comment by StefanBrand** [comment]
Yeah, line 98 shouldn't be too complicated but I'm not sure about lines 115f. I'm really not an Android/Java developer.

**Comment by rengolin** [comment]
Me neither. :)

I think this also has to do with issue #10, so it might not be as simple as I thought.

**Pull request merged**
